name: Generate README

on:
  workflow_dispatch: # manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run reusable action
        uses: Akshat-39/ReadMe-Generator/.github/actions/generate-readme@v1.1.0
        with:
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
